# Generated by Django 2.2.6 on 2019-10-26 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0003_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='movie_name',
            new_name='movie',
        ),
        migrations.RemoveField(
            model_name='room',
            name='time',
        ),
        migrations.AddField(
            model_name='movie',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapi.Movie')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapi.Room')),
            ],
        ),
    ]
