# Generated by Django 2.2.6 on 2019-10-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0004_auto_20191025_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='time',
            field=models.TimeField(),
        ),
    ]
