# Generated by Django 2.2.6 on 2019-10-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0005_auto_20191025_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
